import { GeneralColumnType } from "../types";
export declare function displayGeneralColumnType(columnType: GeneralColumnType): string;
export declare function parseColumnType(s: string | null | undefined): GeneralColumnType;
export declare function isNumericLike(type: GeneralColumnType): boolean;
export declare function isTextLike(type: GeneralColumnType): boolean;
export declare function isBinaryLike(type: GeneralColumnType): boolean;
export declare function isGeometryLike(type: GeneralColumnType): boolean;
export declare function isNotSupportDiffType(type: GeneralColumnType): boolean;
export declare function isDateTimeOrDate(type: GeneralColumnType): boolean;
export declare function isDateTimeOrDateOrTime(type: GeneralColumnType): boolean;
export declare function isTime(type: GeneralColumnType): boolean;
export declare function isUUIDType(type: GeneralColumnType): boolean;
export declare function isJsonLike(type: GeneralColumnType): boolean;
export declare function isBooleanLike(type: GeneralColumnType): boolean;
export declare function isEnumOrSet(type: GeneralColumnType): boolean;
export declare function isArray(type: GeneralColumnType): boolean;
export declare function parseFaIconType(type: GeneralColumnType): string;
